-- =====================================================================
-- 私教 · 交易域建表(购买/权益/预约)
-- pt_private_order, pt_private_order_coupon_rel, pt_member_private_benefit, pt_private_appointment
-- 依据《私教需求文档》第21节 DDL + 《失历健身私教管理后台_详细实现文档》总则0.4/各域§2
-- 字符集 utf8mb4；标 -- 【补充】 的列/索引为需求DDL未给、实现所需(评审项)
-- 可在开发库执行(需确认非生产)
-- =====================================================================

CREATE TABLE `pt_private_order` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `order_no` VARCHAR(32) NOT NULL COMMENT '订单编号，例如 PT202606020001',
  `member_id` BIGINT UNSIGNED NOT NULL COMMENT '会员ID',
  `member_name` VARCHAR(100) DEFAULT NULL COMMENT '会员姓名',
  `member_mobile` VARCHAR(20) DEFAULT NULL COMMENT '会员手机号',
  `product_id` BIGINT UNSIGNED NOT NULL COMMENT '私教商品ID',
  `product_name` VARCHAR(100) NOT NULL COMMENT '购买时商品名称快照',
  `product_type_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '购买时商品类型ID快照',
  `product_type_name` VARCHAR(50) DEFAULT NULL COMMENT '购买时商品类型名称快照',
  `service_type` TINYINT NOT NULL COMMENT '服务类型：1一对一 2一对多',
  `store_id` BIGINT UNSIGNED NOT NULL COMMENT '购买门店ID',
  `lesson_count` INT NOT NULL COMMENT '购买课时数',
  `duration_minutes` INT NOT NULL COMMENT '单次服务时长（分钟）',
  `validity_days` INT NOT NULL COMMENT '有效期天数；长期可约定为-1',
  `original_amount` DECIMAL(10,2) DEFAULT NULL COMMENT '原价金额',
  `payable_amount` DECIMAL(10,2) NOT NULL COMMENT '应付金额',
  `paid_amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '实付金额',
  `refund_amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '累计退款金额',
  `discount_amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '优惠金额',
  `marketing_type` TINYINT NOT NULL DEFAULT 0 COMMENT '营销类型：0普通购买 1拼团 2限时秒杀',
  `marketing_activity_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '营销活动ID',
  `marketing_activity_name` VARCHAR(100) DEFAULT NULL COMMENT '营销活动名称快照',
  `coupon_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '使用优惠券ID',
  `member_coupon_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '会员优惠券ID',
  `coupon_name` VARCHAR(100) DEFAULT NULL COMMENT '使用优惠券名称快照',
  `coupon_discount_amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '优惠券抵扣金额',
  `pay_method` TINYINT DEFAULT NULL COMMENT '支付方式：1微信 2支付宝 3储值 4分期 9其他',
  `pay_status` TINYINT NOT NULL DEFAULT 0 COMMENT '支付状态：0待支付 1部分支付 2已支付 3已退款',
  `order_status` TINYINT NOT NULL DEFAULT 0 COMMENT '订单状态：0待支付 1首付已付 2已结清 3已取消 4已退款',
  `paid_at` DATETIME DEFAULT NULL COMMENT '支付时间',
  `settled_at` DATETIME DEFAULT NULL COMMENT '结清时间',
  `cancel_at` DATETIME DEFAULT NULL COMMENT '取消时间',
  `refund_at` DATETIME DEFAULT NULL COMMENT '退款时间',
  `created_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0否 1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pt_private_order_no` (`order_no`),
  KEY `idx_pt_private_order_member_id` (`member_id`),
  KEY `idx_pt_private_order_product_id` (`product_id`),
  KEY `idx_pt_private_order_product_type_id` (`product_type_id`),
  KEY `idx_pt_private_order_marketing` (`marketing_type`, `marketing_activity_id`),
  KEY `idx_pt_private_order_coupon_id` (`coupon_id`),
  KEY `idx_pt_private_order_member_coupon_id` (`member_coupon_id`),
  KEY `idx_pt_private_order_store_id` (`store_id`),
  KEY `idx_pt_private_order_status` (`order_status`),
  KEY `idx_pt_private_order_paid_at` (`paid_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会员私教购买记录表';

CREATE TABLE `pt_private_order_coupon_rel` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `order_id` BIGINT UNSIGNED NOT NULL COMMENT '私教订单ID',
  `coupon_id` BIGINT UNSIGNED NOT NULL COMMENT '优惠券ID',
  `member_coupon_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '会员优惠券ID',
  `coupon_name` VARCHAR(100) NOT NULL COMMENT '优惠券名称快照',
  `coupon_type` TINYINT NOT NULL COMMENT '券类型：1满减券 2折扣券',
  `discount_amount` DECIMAL(10,2) NOT NULL COMMENT '本次抵扣金额',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pt_private_order_coupon_order_id` (`order_id`),
  KEY `idx_pt_private_order_coupon_coupon_id` (`coupon_id`),
  KEY `idx_pt_private_order_coupon_member_coupon_id` (`member_coupon_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='私教订单优惠券使用记录表';

CREATE TABLE `pt_member_private_benefit` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `benefit_no` VARCHAR(32) NOT NULL COMMENT '权益编号，例如 PE202606020001',
  `order_id` BIGINT UNSIGNED NOT NULL COMMENT '来源私教订单ID',
  `member_id` BIGINT UNSIGNED NOT NULL COMMENT '会员ID',
  `product_id` BIGINT UNSIGNED NOT NULL COMMENT '私教商品ID',
  `store_id` BIGINT UNSIGNED NOT NULL COMMENT '购买门店ID',
  `total_lessons` INT NOT NULL COMMENT '总课时',
  `used_lessons` INT NOT NULL DEFAULT 0 COMMENT '已用课时',
  `frozen_lessons` INT NOT NULL DEFAULT 0 COMMENT '冻结课时，已预约未完成',
  `remaining_lessons` INT NOT NULL COMMENT '剩余可用课时',
  `effective_at` DATETIME NOT NULL COMMENT '生效时间',
  `expire_at` DATETIME DEFAULT NULL COMMENT '到期时间，长期可为空',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '权益状态：1生效中 2已用完 3已过期 4已退款',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pt_member_private_benefit_no` (`benefit_no`),
  KEY `idx_pt_member_private_benefit_order_id` (`order_id`),
  KEY `idx_pt_member_private_benefit_member_id` (`member_id`),
  KEY `idx_pt_member_private_benefit_product_id` (`product_id`),
  KEY `idx_pt_member_private_benefit_store_id` (`store_id`),
  KEY `idx_pt_member_private_benefit_status` (`status`),
  KEY `idx_pt_member_private_benefit_expire_at` (`expire_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会员私教权益表';

CREATE TABLE `pt_private_appointment` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `appointment_no` VARCHAR(32) NOT NULL COMMENT '预约编号，例如 PA202606020001',
  `order_id` BIGINT UNSIGNED NOT NULL COMMENT '私教订单ID',
  `benefit_id` BIGINT UNSIGNED NOT NULL COMMENT '会员私教权益ID',
  `member_id` BIGINT UNSIGNED NOT NULL COMMENT '会员ID',
  `product_id` BIGINT UNSIGNED NOT NULL COMMENT '私教商品ID',
  `coach_id` BIGINT UNSIGNED NOT NULL COMMENT '预约教练ID',
  `store_id` BIGINT UNSIGNED NOT NULL COMMENT '上课门店ID',
  `appointment_date` DATE NOT NULL COMMENT '预约日期',
  `start_time` TIME NOT NULL COMMENT '开始时间',
  `end_time` TIME NOT NULL COMMENT '结束时间',
  `lesson_count` INT NOT NULL DEFAULT 1 COMMENT '本次消耗课时',
  `appointment_status` TINYINT NOT NULL DEFAULT 1 COMMENT '预约状态：1已预约 2已取消 3已完成 4爽约',
  `cancel_reason` VARCHAR(255) DEFAULT NULL COMMENT '取消原因',
  `cancel_at` DATETIME DEFAULT NULL COMMENT '取消时间',
  `finish_at` DATETIME DEFAULT NULL COMMENT '完成时间，完成即视为核销',
  `created_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0否 1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pt_private_appointment_no` (`appointment_no`),
  KEY `idx_pt_private_appointment_order_id` (`order_id`),
  KEY `idx_pt_private_appointment_benefit_id` (`benefit_id`),
  KEY `idx_pt_private_appointment_member_id` (`member_id`),
  KEY `idx_pt_private_appointment_product_id` (`product_id`),
  KEY `idx_pt_private_appointment_coach_time` (`coach_id`, `appointment_date`, `start_time`, `end_time`),
  KEY `idx_pt_private_appointment_store_id` (`store_id`),
  KEY `idx_pt_private_appointment_status` (`appointment_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='私教预约记录表';

