#redis\u914D\u7F6E
project_url=https://shilijsf.shilisports.com

rong_cloud_app_key=pkfcgjstpoxw8

rong_cloud_app_secret =iqv0RmHGy9Vp9V

zt_username =dierxigx

zt_password =ddd
#
baidu_appId=14434925
#apikey
baidu_apiKey=TuD8NXmlcuWFv497Z3yeCxid
#secretKey
baidu_secretKey=Fbfw72jvFIZ5AiKAx9LlUhcoelT30Ses
#groupId  #groupIdList
baidu_groupId=hzjsf_face

#
oxyKcal = 0.2
unoxyKcal = 0.8

#体测报告绑定二维码存储位置
rpro3_qrcode_path = /www/wwwroot/shilijsf.shilisports.com/statics/images/qrcode/
#rpro3_qrcode_path = /www/wwwroot/hzjsf/statics/images/qrcode/
#rpro3_qrcode_path = C:/tmp/qrcode/

#力动二维码存储位置
rido_qrcode_path = /www/wwwroot/shilijsf.shilisports.com/statics/images/rido/qrcode/
#rido_qrcode_path = /www/wwwroot/hzjsf/statics/images/rido/qrcode/
#rido_qrcode_path = C:/tmp/rido/qrcode/