
#匠心测试环境
jdbc.url=jdbc:mysql://127.0.0.1:3306/shilijsf?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
jdbc.username=root
jdbc.password=zjw@123456

#客户老服务器
#jdbc.url=jdbc:mysql://119.23.185.45:3306/hzjsf?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#jdbc.username=hzjsf_root
#jdbc.password=Dgdlchzjsf@42


#新服务器
#jdbc.url=jdbc:mysql://119.23.177.134:3306/hzjsf?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#jdbc.username=hzjsf_root
#jdbc.password=3nepsPbAizPeTzBn